### ISSUE TITLE
Need to always press `i` , or `0` twice

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-js-plugins#109]
Not sure if I need to open this here or in jupyter/notebook, 

But in some case the `i` key respond to press only every other press. This is also the case with `0`.
it affect all panels, terminal, text editor command palette....

No it's not my keyboard , as it works great everywhere else, and its a normal qwerty layout.

Not sure what links `0` and `i`.

Thanks !

**Comment by Carreau** [comment]
> Not sure what links 0 and i.

Respond to myself: interrupt and restart kernel. Though I don't have any notebook open.

**Comment by sccolbert** [comment]
This might have to do with an incorrect selector for these shortcuts. We
saw something similar in command palette which @afshin worked through.

**Comment by afshin** [comment]
https://github.com/jupyter/jupyter-js-plugins/blob/master/src/shortcuts/plugin.ts#L92

They appear to be coded that way. The shortcut is hitting I or 0 twice isn't it?

**Comment by sccolbert** [comment]
and those selectors look fine

**Comment by sccolbert** [comment]
Seems like it's behaving as-written.

**Comment by minrk** [comment]
Yup, the shortcuts for interrupt and restart are double-tap i, 0, respectively. @Carreau are you seeing this for just typing those characters into a text area, or is this when invoking the command?
