### ISSUE TITLE
Design Review of Dialogs

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-plugins#115]
Provide screenshots of existing Dialogs for @cameronoelsen.

**Comment by blink1073** [comment]
<img width="626" alt="4956a1b0-eab9-11e5-825c-8393d876881a" src="https://cloud.githubusercontent.com/assets/2096628/13891365/a8b4bebe-ed1e-11e5-9178-41c87d1ad934.png">

<img width="449" alt="screen shot 2016-03-18 at 3 30 49 pm" src="https://cloud.githubusercontent.com/assets/2096628/13891366/ac203196-ed1e-11e5-91f5-fe3812207243.png">

<img width="627" alt="screen shot 2016-03-18 at 3 30 37 pm" src="https://cloud.githubusercontent.com/assets/2096628/13891371/b0b0626c-ed1e-11e5-93b2-bcac5ef1b6f6.png">

<img width="155" alt="screen shot 2016-03-18 at 3 30 25 pm" src="https://cloud.githubusercontent.com/assets/2096628/13891377/b4a43f60-ed1e-11e5-8158-7dc7b87a847d.png">

<img width="251" alt="screen shot 2016-03-18 at 3 30 12 pm" src="https://cloud.githubusercontent.com/assets/2096628/13891378/b9169ebc-ed1e-11e5-9ef3-d25f958708a4.png">

**Comment by blink1073** [comment]
<img width="199" alt="screen shot 2016-03-18 at 3 34 31 pm" src="https://cloud.githubusercontent.com/assets/2096628/13891415/eec752fe-ed1e-11e5-83bf-4d61278685b7.png">

**Comment by blink1073** [comment]
<img width="451" alt="screen shot 2016-03-21 at 2 40 49 pm" src="https://cloud.githubusercontent.com/assets/2096628/13931816/15ce3e16-ef73-11e5-9454-c83f564a7516.png">

**Comment by cameronoelsen** [comment]
Here is my first pass at the dialogs:

## Close Without Saving

![close without saving](https://cloud.githubusercontent.com/assets/6437976/13937942/35d4ea44-ef86-11e5-9e6a-63e2e444fa95.png)

## Create New Notebook

![create new notebook](https://cloud.githubusercontent.com/assets/6437976/13937944/38cecb8e-ef86-11e5-9eee-5c0ab37db737.png)

## Error

![error](https://cloud.githubusercontent.com/assets/6437976/13937948/4359d044-ef86-11e5-9078-b4f30bf5ae50.png)

## Restart Kernel

![restart kernel](https://cloud.githubusercontent.com/assets/6437976/13937954/4984fe30-ef86-11e5-95b4-1b178156427c.png)

## Shutdown Kernel

![shutdown kernel](https://cloud.githubusercontent.com/assets/6437976/13937957/50bbb9dc-ef86-11e5-861c-5acc6def947b.png)

## Trust Notebook

![trust](https://cloud.githubusercontent.com/assets/6437976/13937959/57f6e212-ef86-11e5-93fd-29be9dacb737.png)

I am still unsure if the cancel button should be on the right or if the done button should be, as well as which button the accent color should be on. I put the accent color on the Cancel button throughout the designs since I have seen a few other websites do this and I am assuming that this is being done so that if a user accidently clicks on something, when you click "Enter" on your keyboard, it cancels the action to ensure that the user meant to perform the task. But, I will need to do some further research to make sure that these user interactions are correct. Besides this, what are your guys' thoughts?

**Comment by blink1073** [comment]
Thanks @cameronoelsen, see https://github.com/jupyter/notebook/issues/742 for @ellisonbg's thoughts on the matter.  My preference would be for the "do action" to be highlighted, and take on an appropriate color based on whether the action is "dangerous".

**Comment by blink1073** [comment]
Also, the "refresh error" should probably have a better name/explanation.  What it really means is that we lost our connection to the server and were unable to refresh the directory listing.  Maybe:

Title: Server Connection Lost
Body: Unable to refresh the directory listing due to lost server connection.

**Comment by blink1073** [comment]
Also note that the dialogs should be modal only to their respective pane.

**Comment by cameronoelsen** [comment]
Awesome, here are the changes. The insight/article Safia posted about the buttons fixed that problem and I made sure that the modals are only in their respective windows. I like the look of these more already!

## Close Without Saving

![close without saving 2](https://cloud.githubusercontent.com/assets/6437976/13938901/2b15a6be-ef8d-11e5-8c11-c0e6278f9817.png)

## Create New Notebook

![create new notebook 2](https://cloud.githubusercontent.com/assets/6437976/13938904/3556211c-ef8d-11e5-8948-9a398650ca8b.png)

## Error

![error 2](https://cloud.githubusercontent.com/assets/6437976/13938908/3dcb7838-ef8d-11e5-9594-6495a9967c3d.png)

## Restart Kernel

![restart kernel 2](https://cloud.githubusercontent.com/assets/6437976/13938913/4745e7d6-ef8d-11e5-9def-8f695dcfb134.png)

## Shutdown Kernel

![shutdown kernel 2](https://cloud.githubusercontent.com/assets/6437976/13938916/4c575dc2-ef8d-11e5-8d80-dddb92459703.png)

## Trust Notebook

![trust 2](https://cloud.githubusercontent.com/assets/6437976/13938920/5567ab60-ef8d-11e5-88b6-88e8d3e5041f.png)

**Comment by blink1073** [comment]
Looking good, got some colors for me :smile:?

**Comment by cameronoelsen** [comment]
@blink1073 Making a specification sheet as we speak :)

**Comment by cameronoelsen** [comment]
## Dialog Color Specification

![specification](https://cloud.githubusercontent.com/assets/6437976/13939268/c4965470-ef90-11e5-9470-159b6e5f72de.png)

## Dialog Margin/Padding

![margin](https://cloud.githubusercontent.com/assets/6437976/13939274/d4ace716-ef90-11e5-907d-9f9e24a1dc25.png)

**Comment by blink1073** [comment]
Sweet, great work as usual Cameron, I'll style them tomorrow.

**Comment by minrk** [comment]
Thanks, @cameronoelsen!

**Comment by blink1073** [comment]
One more for you @cameronoelsen:

<img width="417" alt="screen shot 2016-03-22 at 8 17 05 am" src="https://cloud.githubusercontent.com/assets/2096628/13952808/89b6c774-f006-11e5-9a9e-4d2586629495.png">

**Comment by blink1073** [comment]
Status:

<img width="494" alt="screen shot 2016-03-22 at 9 35 15 am" src="https://cloud.githubusercontent.com/assets/2096628/13955111/7505e76e-f011-11e5-83b0-e85339d21e45.png">

**Comment by blink1073** [comment]
@ellisonbg, it looks like the preference is to give the "action" button focus based on the existing ui, do we want to add `outline` styling?

<img width="299" alt="screen shot 2016-03-22 at 11 04 21 am" src="https://cloud.githubusercontent.com/assets/2096628/13958381/da6387ea-f01d-11e5-86b2-2ba8e7beacba.png">

**Comment by ellisonbg** [comment]
I wouldn't do the extra outline styling. Both Material Design and Metro
don't add any additional styling to the default button. They don't even
always style it differently...

On Tue, Mar 22, 2016 at 9:04 AM, Steven Silvester notifications@github.com
wrote:

> @ellisonbg https://github.com/ellisonbg, it looks like the preference
> is to give the "action" button focus based on the existing ui, do we want
> to add outline styling?
> 
> [image: screen shot 2016-03-22 at 11 04 21 am]
> https://cloud.githubusercontent.com/assets/2096628/13958381/da6387ea-f01d-11e5-86b2-2ba8e7beacba.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-plugins/issues/115#issuecomment-199882242

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
@cameronoelsen, any thoughts on centering the buttons vertically rather than pinning them to the left?

**Comment by cameronoelsen** [comment]
@blink1073 Definitely think that all of the content should be left justified (title, description, buttons). It also seems that the buttons are a little too big. Also, the dialogs shouldnt have a border but rather just a shadow.

**Comment by blink1073** [comment]
Ah!  I totally missed that text and header were left-justified.

**Comment by blink1073** [comment]
<img width="498" alt="screen shot 2016-03-22 at 12 49 29 pm" src="https://cloud.githubusercontent.com/assets/2096628/13961906/8df2d6ea-f02c-11e5-89aa-fd3e2ea3bc3f.png">

**Comment by blink1073** [comment]
There was still a bit of padding on the button, fixed:

<img width="329" alt="screen shot 2016-03-22 at 12 52 06 pm" src="https://cloud.githubusercontent.com/assets/2096628/13961979/eabb2e54-f02c-11e5-9375-c0846c9291e3.png">

**Comment by cameronoelsen** [comment]
@blink1073 Is there a way to make the input field line up with the right side of the OK button? Also lookin' slick.

**Comment by blink1073** [comment]
<img width="335" alt="screen shot 2016-03-22 at 1 07 11 pm" src="https://cloud.githubusercontent.com/assets/2096628/13962456/04f5901e-f02f-11e5-9f92-b824cc3eb5fe.png">

**Comment by blink1073** [comment]
All that's missing is dropdown styling ;)

**Comment by cameronoelsen** [comment]
@blink1073 Looks like there is some extra padding or margin on the right side of that, the left and right side don't look equal. Also, it looks like there is an outside border on the dialog, can we swap that out for like a 2px box shadow and see how that looks? Figuring out right now how I want the dropdown to look like :+1:

**Comment by blink1073** [comment]
Thanks, tweaking some more...

**Comment by blink1073** [comment]
This is with `box-shadow: 2px 2px 2px black;`:

<img width="325" alt="screen shot 2016-03-22 at 1 15 21 pm" src="https://cloud.githubusercontent.com/assets/2096628/13962701/33b9a880-f030-11e5-8b60-85033008c05a.png">

**Comment by cameronoelsen** [comment]
Try this out box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.5);

**Comment by blink1073** [comment]
<img width="324" alt="screen shot 2016-03-22 at 1 18 10 pm" src="https://cloud.githubusercontent.com/assets/2096628/13962785/8c7f8052-f030-11e5-9576-6fcacd1110ac.png">

**Comment by cameronoelsen** [comment]
That looks great but I only want the shadow to be in the y-direction and not the x-direction

**Comment by blink1073** [comment]
Oh, I had updated just the color:

<img width="320" alt="screen shot 2016-03-22 at 1 19 46 pm" src="https://cloud.githubusercontent.com/assets/2096628/13962837/c54ab5b4-f030-11e5-9574-050f3157b792.png">

**Comment by cameronoelsen** [comment]
Beautiful :heart_eyes:

**Comment by blink1073** [comment]
Thoughts on using cap-case and using "Okay"?

**Comment by cameronoelsen** [comment]
Are we able to change the OK button per different dialog? You can see in my mockups that, if possible, we can put the action in that box

**Comment by cameronoelsen** [comment]
I personally have no preference on OK vs OKAY but have seen OK used more in interfaces in the past

**Comment by blink1073** [comment]
Yes, the dialogs have the action text you used above.  I mean capitalizing just the first letter.

**Comment by blink1073** [comment]
<img width="318" alt="screen shot 2016-03-22 at 1 25 19 pm" src="https://cloud.githubusercontent.com/assets/2096628/13963001/8d812f36-f031-11e5-808b-daa069a2e42a.png">

**Comment by cameronoelsen** [comment]
I am :+1: on capitalizing the entire word. This is one of the conventions I used from material design and I think it makes the buttons look standardized

**Comment by cameronoelsen** [comment]
Also:

## Selecting kernel

![select](https://cloud.githubusercontent.com/assets/6437976/13963126/5d3ac856-f021-11e5-9b8c-8a7da484063a.png)

**Comment by cameronoelsen** [comment]
Getting the colors of that right now, it uses the same margins as the other dialogs

**Comment by blink1073** [comment]
Sweet!  Adding standard dropdown selector now.

**Comment by cameronoelsen** [comment]
![dropdown spec](https://cloud.githubusercontent.com/assets/6437976/13963538/f91b09c4-f022-11e5-846c-d5a65bd4dbae.png)

**Comment by cameronoelsen** [comment]
Also wasn't sure if you had control over the arrow in the dropdown so I just colored it. May want to change the margins depending what it looks like when you make the other styling

**Comment by blink1073** [comment]
Did you want to define the `<input>` tag similarly?

**Comment by cameronoelsen** [comment]
I think the input tag looks pretty good actually, looking at that, I made a change to the background color of the dropdown so it is lighter than the dialog (looks nicer and tells the user that it is it's own element). The color is just white #FFFFFF

Also there is a 2px border radius that I accidently left out. That should be applied to the <input> tag

![dropdown](https://cloud.githubusercontent.com/assets/6437976/13963778/f55ef614-f023-11e5-8dd0-9b04cfca147b.png)

**Comment by blink1073** [comment]
<img width="321" alt="screen shot 2016-03-22 at 2 06 16 pm" src="https://cloud.githubusercontent.com/assets/2096628/13964348/4911d6c4-f037-11e5-9247-b5ff9402a3d8.png">

**Comment by cameronoelsen** [comment]
2px border radius on the input field and that should be good!

**Comment by blink1073** [comment]
<img width="319" alt="screen shot 2016-03-22 at 2 08 36 pm" src="https://cloud.githubusercontent.com/assets/2096628/13964416/9bc7c32e-f037-11e5-89dc-c2ede1e7483d.png">

My demo doesn't have a dropdown in it, adding one...

**Comment by blink1073** [comment]
The arrow can't be styled from what I can tell:

<img width="324" alt="screen shot 2016-03-22 at 3 09 39 pm" src="https://cloud.githubusercontent.com/assets/2096628/13966379/264203f4-f040-11e5-9627-6dbabb7c277b.png">

**Comment by blink1073** [comment]
Slimmed down the text-based one:

<img width="362" alt="screen shot 2016-03-22 at 3 21 01 pm" src="https://cloud.githubusercontent.com/assets/2096628/13966713/c5377114-f041-11e5-9f9f-dbe7b5ded145.png">

**Comment by blink1073** [comment]
Even slimmer (now all the dialogs are 290px wide):

<img width="316" alt="screen shot 2016-03-22 at 3 27 39 pm" src="https://cloud.githubusercontent.com/assets/2096628/13966921/a2b9b682-f042-11e5-9c36-8ac349aac12d.png">

**Comment by blink1073** [comment]
Whoops, it is supposed to be 300px, now finished:

<img width="323" alt="screen shot 2016-03-22 at 3 30 06 pm" src="https://cloud.githubusercontent.com/assets/2096628/13966989/fd377644-f042-11e5-800c-cb2c5f6853ef.png">

**Comment by sccolbert** [comment]
The left aligned dismiss button looks weird to me. I think most dialogs
right align the buttons, right?

**Comment by blink1073** [comment]
Agreed: https://www.google.com/design/spec/components/buttons.html#buttons-style

<img width="309" alt="screen shot 2016-03-23 at 8 01 03 am" src="https://cloud.githubusercontent.com/assets/2096628/13985903/6fdbdc5a-f0cd-11e5-8919-240128a5fbd0.png">

**Comment by blink1073** [comment]
"Button alignment: Right edge for LTR scripts"

**Comment by ellisonbg** [comment]
I opened this newer issue about dialogs here: https://github.com/jupyter/jupyter-js-ui/issues/98

Where is the right place for JupyterLab issues? Central? Per repo, depending on what it is?

**Comment by willingc** [comment]
@ellisonbg @blink1073 Is the warning about trusted notebooks accurate? It reads a little funny. I would think that an 'untrusted' notebook could be malicious.

**Comment by blink1073** [comment]
It could perhaps be worded better.  The point is, if it is _marked_ as trusted, any malicious code that it happened to contain would be executed.  I had copied the phrasing from the existing notebook.

**Comment by blink1073** [comment]
@ellisonbg,  I would argue that `jupyter-js-ui`, `jupyter-js-notebook`, and `jupyter-js-plugins` should be merged into a single `jupyterlab` with appropriate subfolders, the same way we are squeezing `phosphor` down.  The current split is causing a lot of confusion.

cc @jasongrout @SylvainCorlay

**Comment by sccolbert** [comment]
:+1: to fewer repos. Let's just use well-named paths and rely on webpack to pare things down. Any argument about saving disk space is null and void when you look at the dependency graph of a typical node package :)

**Comment by ellisonbg** [comment]
Or maybe jupyter-js-jupyterlab as we will likely have a jupyterlab python
package?

On Fri, May 27, 2016 at 1:52 PM, S. Chris Colbert notifications@github.com
wrote:

> 👍 to fewer repos. Let's just use well-named paths and rely on webpack to
> pare things down. Any argument about saving disk space is null and void
> when you look at the dependency graph of a typical node package :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jupyter/jupyter-js-plugins/issues/115#issuecomment-222250558,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABr0FYTNKN1YpEjFejD2rJ9jQ3Sx1yKks5qF1mYgaJpZM4H0C0v
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
Shouldn't the python portion be minimal? We could just include the Python in the same repo.

**Comment by SylvainCorlay** [comment]
It makes sense for the server extension python to be with the javascript of jupyterlab.

If we want to separate things, we could have that javascript be minimal and only be the webpack bundler + package.json listing the plugins located in separates repos.

**Comment by ellisonbg** [comment]
I can make a JupyterLab meeting this Friday 9-10am. Would be great to talk
about the package/repo organization.

On Mon, May 30, 2016 at 5:46 PM, Sylvain Corlay notifications@github.com
wrote:

> It makes sense for the server extension python to be with the javascript
> of jupyterlab.
> 
> If we want to separate things, we could have that javascript be minimal
> and only be the webpack bundler + package.json listing the plugins located
> in separates repos.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jupyter/jupyter-js-plugins/issues/115#issuecomment-222570472,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABr0EWGWodPETm_M0sh0zs92Rg2rRxfks5qG4TugaJpZM4H0C0v
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
Before I continue to iterate on the dialogs, I wanted to know what we think about where dialogs should be displayed (within each plugin or the entire screen):

### Within the plugin

#### Version 1 (Popup Dialog)

![restartkernel2](https://cloud.githubusercontent.com/assets/6437976/15759989/0fabca30-28c6-11e6-9731-6e2ed50ccf56.png)

#### Version 2 (Inline/dropdown Dialog)

![inlinerestart](https://cloud.githubusercontent.com/assets/6437976/15759789/371429c4-28c5-11e6-925b-8927a2579335.png)

### Covering the entire environment

#### Version 1 (Popup Dialog)

![restartkernel](https://cloud.githubusercontent.com/assets/6437976/15759816/4d8ac186-28c5-11e6-92a9-1283317b9325.png)

I personally like the approach of covering the entire environment for all dialogs, seeing I haven't seen any other platform do per-plugin dialogs. I talked with Matt as well and he agrees. I just think using the fullscreen, full attention dialog is standard. What do you guys think? I am not set on all of the colors, but I made the buttons drastically smaller and made the fonts standardized with the rest of JupyterLab. We also were straying away from the orange highlight color for the actions and highlights!

**Comment by sccolbert** [comment]
I like Version 1 or Version 3. Version 3 is simpler to implement, though not by all that much. Who is Matt?

**Comment by cameronoelsen** [comment]
@sccolbert Matt is one of the new design interns that sits next to me in the SLO office, just happened to be passing by as I was writing the comment 👍  I like version 3 as well @sccolbert

**Comment by ellisonbg** [comment]
I probably prefer 3 as well. Issues with 1:
- We will end up trying to show dialog in very small panels sometimes. That
  is a pretty miserable user experience.
- Most of these dialogs are should to be globally-modal, and block the rest
  of the entire UI until the user deals with it. An example: if a user has a
  notebook opened twice in two different panels (same model & 2 views), what
  happens when one panel shows a dialog? Does the other show the same dialog?
  What happens if a use interaction messes up the state implied by the dialog.

So strong preference for 3.

On Thu, Jun 2, 2016 at 1:31 PM, Cameron Oelsen notifications@github.com
wrote:

> @sccolbert https://github.com/sccolbert Matt is one of the new design
> interns that sits next to me in the SLO office, just happened to be passing
> by as I was writing the comment 👍 I like version 3 as well @sccolbert
> https://github.com/sccolbert
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jupyter/jupyter-js-plugins/issues/115#issuecomment-223412925,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABr0LH2Ehfu-INa86OJoI-xBYawZiLjks5qHz2lgaJpZM4H0C0v
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
@ellisonbg brings up some great points. They increase my preference to a strong vote for version 3.

**Comment by blink1073** [comment]
Version 3 works for me as well.

**Comment by jasongrout** [comment]
+1 for version 3 _if_ there is a good way to indicate which panel the dialog is for. The other ways make it clear which tab the dialog is acting on. With option 3, there's no way to know other than trying to remember.

That's one thing I really like about OS X modal dialogs that drop down in the application window - it's very clear what is going to be affected, and it's easy to do other stuff while that particular window is on hold waiting for an answer.

**Comment by jasongrout** [comment]
For example, perhaps the panel causing the dialog to appear can have a heavy bright border or something. I don't think it's necessary to be able to see clearly everything in the tab, but some coarse-grained indication of which tab I'm interacting with would be a huge help.

**Comment by willingc** [comment]
> > +1 for version 3 if there is a good way to indicate which panel the dialog is for. 

I would encourage some sort of indication within the dialog box too. Perhaps the name(s) of the tabs impacted by the dialog action could also be listed.

**Comment by blink1073** [comment]
Good call @willingc, especially if the tab itself would be obscured.

**Comment by blink1073** [comment]
Closing, as design has moved to JupyterLab.
