### ISSUE TITLE
Move transformime to be a service in the application

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-plugins#130]
In order for the widget manager to be at the notebook plugin level, we need the output renderer (transformime) to also be at that level so that the widget manager can register a renderer for the `application/vnd.jupyter.widget` mimetype.

Here's a quick sketch of a plan of action:
1. Move transformime from the jupyter-js-notebook repo up to this repo, perhaps in the notebook plugin directory for now. Eventually, we might make it a separate service provided by a plugin?
2. In the notebook plugin.ts file, construct the transformime instance and pass it to the notebook. We'll have to change the notebook widget to accept a transformime instance that it will use to render outputs.
3. Construct the widgetmanager and make a new transformime renderer that uses the widget manager to render the mimetype `application/vnd.jupyter.widget` (with data being the model id, and returning a phosphor widget). Register this new transformime renderer.

New plan of action:
- [x] Create rendermime and renderers directories in jupyter-js-ui. Put the registration and default plugins in those, respectively.
- [x] Create plugins for rendermime and the renderers. The renderers plugin depends on the rendermime plugin and registers the default renderers.
- [x] The notebook plugin depends on the rendermime plugin, and passes the rendermime object into the notebook widget. The notebook widget then uses that rendermime object to do the rendering.
- [x] Scratch katex for now - we'll just use mathjax
- [x] move the latex.ts file to jupyter-js-ui/src/renderers/.
- [x] Eventually, make a markdown renderer. Then the notebook uses rendermime to render markdown cells as well. - POSTPONED

CC @afshin, @blink1073, @jdfreder, @sccolbert.

**Comment by dwillmer** [comment]
I realise this is potentially a non-technical issue, but do we even really need transformime?

It's another dependency (which as we've all seen in the last 24 hours is a bad thing :stuck_out_tongue: ), but it really doesn't give us much at this point. Transformime is just converting mime types to some object which knows how to build something useful; it's not typed, and needs modifications for jupyterlab anyway - why don't we just implement a simple, pluggable system that does what we need without using it?

**Comment by blink1073** [comment]
I don't see what is wrong with leaving transformime as part of `jupyter-js-notebook`.

**Comment by blink1073** [comment]
Or, if desired, it could be in `jupyter-js-ui`.

**Comment by sccolbert** [comment]
I'm not completely following the reasoning for this. Can we have a call about it tomorrow?

**Comment by jasongrout** [comment]
@dwillmer - that's what I'm basically proposing. We rewrote transformime to be a typed pluggable rendering system like you said (https://github.com/jupyter/jupyter-js-notebook/pull/119). We should perhaps rename it so it's not so confusing. What I'm suggesting is that this new transformime shouldn't live at the jupyter-js-notebook level since it's needed by the widget manager and possibly other plugins to provide rendering capabilities to notebooks. Instead, I think we should bring our version of transformime up to the jupyter-js-plugins repo, make it a separate plugin that provides the rendering service, and then have the notebook plugin depend on it as part of the dependency injection framework.  We make it a separate plugin so that any plugin can register new renderers.

Is that clearer?

**Comment by jasongrout** [comment]
I'm open to good names for our transformime system: mimerender? rendermime? (I like "render" rather than "transform")

**Comment by sccolbert** [comment]
If it's needed by the notebook, should it really be a plugin? That would force the notebook to have a phosphide dependency, wouldn't it?

**Comment by jasongrout** [comment]
I would say the rendering service plugin is needed by the notebook _plugin_. When the notebook plugin constructs a notebook, it hands it a single function/object to do the rendering.

Are you suggesting that instead of having the renderer be a plugin on its own, we should instead have the notebook plugin provide a rendering registration service, and have the widget manager register with that? Actually, that sounds like a good way to go too.

**Comment by sccolbert** [comment]
I'm not suggesting anything particular at this point. Just trying to get on the same page as you wrt the situation. I'm still not fully there yet :)

**Comment by jasongrout** [comment]
Okay, let's talk tomorrow.

**Comment by jasongrout** [comment]
Gathering my thoughts about what we need:
1. We don't want widgets to be a part of jupyter-js-notebook. Instead, we want widgets to be a separate thing, on a level playing field with other possible components for rendering content (e.g., a matplotlib interactive output, an altair component that renders charts according to the vega spec, etc.)
2. Such components need to be able to register a renderer for various mimetypes in the notebook output areas.  The notebook uses these registered renderers to render outputs.
3. In at least one case (the output widget), the component needs to be able to use the notebook output renderer.

Our extension mechanism is top-level plugins in phosphide. Because of (1), we need the renderer service to be exposed to outside plugins, not just an internal notebook thing. Because of (2) and (3), we need the renderer service to provide both ways to register mimetype renderers and to use the renderer as a whole to render a mimebundle.

We could make the registration and render services provided by a notebook plugin, or by a separate plugin that the notebook plugin then uses. At the moment, I can see either way working.

**Comment by blink1073** [comment]
I think that the basic service should be part of `jupyter-js-ui`, with the "plugin" part added in `jupyter-js-plugins`, similar to the `phosphor-keymap`/`phosphide` shortcuts layering.

**Comment by jasongrout** [comment]
That sounds reasonable to me.

**Comment by jasongrout** [comment]
Grr, sorry, wrong button.

**Comment by rgbkrk** [comment]
> I realise this is potentially a non-technical issue, but do we even really need transformime? It's another dependency (which as we've all seen in the last 24 hours is a bad thing :stuck_out_tongue: ) ... Transformime is just converting mime types to some object which knows how to build something useful; it's not typed, and needs modifications for jupyterlab anyway

No one is opposed to making transformime be typed and everyone that's contributed to it has complete access to merging PRs on it and shipping new releases. If you prefer transformime to be in Jupyter, put up an enhancement proposal for inclusion. PRs are not ignored on transformime. That's more a question of whether and how you want to build a community.

As for if you want a different design over in `jupyter-js-notebook`, pick the flow and API that works for you. Seems like that's going fairly well in https://github.com/jupyter/jupyter-js-notebook/pull/119. The first API was put in place for other frontends to use (sidecar, Hydrogen). You're free to explore and iterate. The main reason we want a library for something is so that we have consistency amongst those frontends.

**Comment by jasongrout** [comment]
@rgbkrk if you want, feel free to jump on appear.in/jupyter, where we're discussing this.

**Comment by jasongrout** [comment]
Conclusions:
1. Create rendermime and renderers directories in jupyter-js-ui. Put the registration and default plugins in those, respectively.
2. Create plugins for rendermime and the renderers. The renderers plugin depends on the rendermime plugin and registers the default renderers.
3. The notebook plugin depends on the rendermime plugin, and passes the rendermime object into the notebook widget. The notebook widget then uses that rendermime object to do the rendering.
4. Scratch katex for now - we'll just use mathjax
5. move the latex.ts file to jupyter-js-ui/src/renderers/.
6. Eventually, make a markdown renderer. Then the notebook uses rendermime to render markdown cells as well.

**Comment by blink1073** [comment]
Marking this as complete.
