### ISSUE TITLE
Dragging onto dock area doesn't make new tab panels

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-plugins#136]
I noticed this with a fresh checkout of the current master (https://github.com/jupyter/jupyter-js-plugins/tree/d2b5409463a01435a4695fe3cbc6f9dac3ba6592): When dragging tabs, I can't get the dock area to split into multiple tab areas.

![tabs](https://cloud.githubusercontent.com/assets/192614/14044469/7fce10e2-f267-11e5-9128-e7aa055d7afe.gif)

CC @blink1073, @sccolbert

**Comment by dwillmer** [comment]
Do you have anything in the console?

**Comment by jasongrout** [comment]
Nope. I did have a note that a kernel was starting up when I first dragged the notebook over (even though the tab didn't show up, apparently the kernel still started up). No errors, though.

**Comment by jasongrout** [comment]
Can someone reproduce this, or is it working for everyone?

**Comment by blink1073** [comment]
I'll try it in a few minutes

**Comment by blink1073** [comment]
Not seeing this in Chrome or Firefox on OSX.

**Comment by blink1073** [comment]
Can you set a debug point here and see if it is being called?:

https://github.com/jupyter/jupyter-js-plugins/blob/master/src/notebook/plugin.ts#L556

**Comment by blink1073** [comment]
Also here:

https://github.com/jupyter/jupyter-js-plugins/blob/master/src/filebrowser/plugin.ts#L70

**Comment by jasongrout** [comment]
Your first debug point is hit (in notebook/plugin). It looks like a Notebook widget is created, but then this condition is triggered: https://github.com/phosphorjs/phosphor-dockpanel/blob/943e5519f074945f0a9d22723b8a36bebd17ae6b/src/index.ts#L376

Indeed, when I'm at that spot in the code, `widget instanceof phosphor_widget_1.Widget` in the console gives `false`.

**Comment by sccolbert** [comment]
Try running npm dedupe. Looks like you have two versions of phosphor-widget
installed.

**Comment by blink1073** [comment]
@jasongrout, is this fixed now that #140 is merged?

**Comment by jasongrout** [comment]
Things work now. Thanks!
