### ISSUE TITLE
API Docs link in README.md is 404

### ISSUE THREAD

**Issue by JoeGermuska** [jupyter/jupyter-js-plugins#142]
As a total newb to this project, I was hoping to read those to learn what it's about. Alternatively, or in addition, consider adding a paragraph at the top of the README.md saying what it's for?

**Comment by blink1073** [comment]
Hi @JoeGermuska, thank you for pointing this out.  The tool that builds our API docs is currently not compatible with our code base (we are tracking it in https://github.com/jupyter/jupyter-js-notebook/issues/118).  I created #144 to address your concerns.
