### ISSUE TITLE
notebook asks about closing kernel when tab dragged

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-plugins#159]
With current master (d06529b7fe81c769a20de33b977e83cdc5a87b68), I get the following behavior:

![restart kernel](https://cloud.githubusercontent.com/assets/192614/14611795/0ef680d0-0562-11e6-8e45-fe23952b5c16.gif)

It asks about restarting the kernel when I drag the tab the first time, and on top of that, the dialog box is in the middle of the notebook, not in middle of the visible area.

**Comment by blink1073** [comment]
I'm looking into this now.

**Comment by jasongrout** [comment]
Thanks. Let me know if you can't reproduce it.

**Comment by blink1073** [comment]
Both confirmed, both will need to be fixed in `jupyter-js-notebook`.
