### ISSUE TITLE
Unable to open a terminal

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter-js-plugins#39]
Hey, I'm excited to see most of this working.  I know it's still WIP, but I thought I could help by testing.   I checked out https://github.com/jupyter/notebook/pull/972 and re-ran setup.py.  I was unable to start a terminal, I see this error:

```
Error in command 'jupyter-plugins:new:terminal': DOMException: Failed to construct 'WebSocket': The URL 'terminals/websocket/1' is invalid.(…)CommandRegistry.execute @ bundle.js:12227
bundle.js:12227 Error in command 'jupyter-plugins:new:terminal': DOMException: Failed to construct 'WebSocket': The URL 'terminals/websocket/2' is invalid.(…)CommandRegistry.execute @ bundle.js:12227
```

**Comment by blink1073** [comment]
Thanks, fixed through upgrades to utils, terminal, and plugins.
