### ISSUE TITLE
losing orange top border on active tab

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-plugins#69]
@sccolbert - On current master (2fbceb105eeab0e2aafe13b52c891011d819a1b7), it seems that when I open a few files, and then open a notebook, the dock area active tab loses the orange top border of the actual tab.

I'll look at this Monday more...

**Comment by sccolbert** [comment]
@jasongrout can you post a screen cap so I can reproduce?

**Comment by jasongrout** [comment]
Yep, I'll do that Monday.

**Comment by jasongrout** [comment]
![missinghighlight](https://cloud.githubusercontent.com/assets/192614/13055168/cccce6c0-d3db-11e5-9d81-aa2770eb078e.gif)

**Comment by sccolbert** [comment]
do you have any exceptions in your console?

**Comment by jasongrout** [comment]
No, no exceptions. Does it work for you?

**Comment by jasongrout** [comment]
Just to be clear, I did

```
rm -rf node_modules
rm -rf example/node_modules
npm install
npm run clean
npm run build
cd example
npm install
rm -rf build
npm run build
python main.py
```

**Comment by sccolbert** [comment]
![browser](https://cloud.githubusercontent.com/assets/137289/13055833/8db68366-d3df-11e5-9e2a-74f2ba0926e0.gif)

**Comment by jasongrout** [comment]
Okay, I'll try to track it down on my end.

**Comment by sccolbert** [comment]
works for me on Windows/Chrome

**Comment by sccolbert** [comment]
What does your element inspector show for that tab?

**Comment by jasongrout** [comment]
This is on OS X.
- It works in firefox, not in Chrome
- the `.p-TabBar-tab.p-mod-current` has border-top style `1px solid #F27624`, and the computed border shows .909px. both before and after the border disappears
- After the border disappears, if I change the border-top style to `2px solid #F27624`, the top border reappears with what seems to be the same height, but the computed height is now ...

_Edit: it just started working. Very weird._

**Comment by jasongrout** [comment]
I'll close this for now, and reopen if it starts happening again.  The only thing I can think of is stale css, but I had the dev tools open, which should eliminate caching.

**Comment by sccolbert** [comment]
Ah ok. This is a rendering bug in chrome on retina displays. Sometimes 1px lines are not rendered due to internal rounding errors (assumption). I see this same thing on the dock panel example with the 1px solid panel borders during resizing and overlay positioning (sometimes).

**Comment by jasongrout** [comment]
Okay, that makes sense.  When I saw the 1px border was being converted to
.909px, I thought it might be a rounding issue.

**Comment by jasongrout** [comment]
By the way, the screencap and what I was investigating was on a 1440p
monitor, not a retina display.

**Comment by sccolbert** [comment]
I think chrome might still use the same internal scaling logic on the external display (guess). But that's good to know it's a chrome/mac issue in general, and not display specific.
